# fly.toml app configuration file generated for reactivities-hengsomnang-twilight-resonance-6161 on 2024-01-29T16:54:28+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'reactivities-hengsomnang-twilight-resonance-6161'
primary_region = 'sin'

[build]
  image = 'hengsomnang/reactivities:latest'

[env]
ASPNETCORE_URLS="http://+:8080"
Cloudinary__CloudName="dhqiuvcw4"
Cloudinary__ApiKey="785953993297427"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
